### PR TITLE
Add GitHub workflow and tests

### PR DESCRIPTION
**Pull request by KurtGokhan**
- Adds GH workflow that will check formatting, lint, test and build.
- Adds some tests for `light-dark`. Will add other tests later.
- Uses Jest snapshots to make it easier to test. Snapshots can be updated with `yarn test -u`. Snapshots must be manually verified after updating.

### CODE REVIEW

**Comment by rtivital** [comment]
@KurtGokhan please let me know when PR is done and ready for review

**Comment by KurtGokhan** [comment]
Sorry for the confusion. My intention was to write the tests in another PR if this one looked good already. Anyway, the rest are done. It is ready for review @rtivital 

Here is the coverage:

image

**Comment by KurtGokhan** [comment]
Btw, I also updated an issue with rem-em where it matched the end of the word instead of the whole word. It was matching functions like `theorem(32px)` or `poem(32px)`. There is a test case for that.

**Comment by rtivital** [comment]
Thanks @KurtGokhan, great job!

**Pull request merged**
